version: '3'
services:
  front:
    build: ./front
    container_name: front
    volumes:
      - ./front:/usr/src/app
    ports:
      - 3000:3000
  server:
    build: ./server
    container_name: server
    volumes:
      - ./server:/app
    ports:
      - 3001:3001