version: '3'
services:
  front:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3001:3001
